import './flat-ui-body.styl'

import '../section-standard-buttons/section-standard-buttons'
import '../section-arrow-buttons/section-arrow-buttons'
import '../section-percentages-and-pie-charts/section-percentages-and-pie-charts'
import '../section-sliders/section-sliders' 
import '../section-stages/section-stages'
import '../section-form-elements/section-form-elements' 
import '../section-news-and-events/section-news-and-events'
import '../section-location/section-location'  
import '../section-calendar/section-calendar' 
import '../section-messenger/section-messenger'